# Generated by Django 6.0.3 on 2026-04-05 23:56
# Modified: columns already exist in DB — use SeparateDatabaseAndState for idempotency

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gest_saas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # ---- Already in DB: wrap state-only ----
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='billetage',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billetages', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='chargeadminis',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges_adminis', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='decaissement',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decaissements', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='encaissement',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encaissements', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='historicalbilletage',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='historicalchargeadminis',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='historicaldecaissement',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='historicalencaissement',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='historicalsoldejour',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        # ---- prevision.entreprise does NOT exist yet: real AddField ----
        migrations.AddField(
            model_name='prevision',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previsions', to='Gest_saas.entreprise'),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='soldejour',
                    name='entreprise',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soldes_jour', to='Gest_saas.entreprise'),
                ),
            ],
            database_operations=[],
        ),
        # ---- gerant.user unique constraint already in DB ----
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='gerant',
                    name='user',
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gerant', to=settings.AUTH_USER_MODEL),
                ),
            ],
            database_operations=[],
        ),
        # ---- soldejour.date_saisie unique already removed; unique_together already set ----
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='historicalsoldejour',
                    name='date_saisie',
                    field=models.DateField(),
                ),
                migrations.AlterField(
                    model_name='soldejour',
                    name='date_saisie',
                    field=models.DateField(),
                ),
                migrations.AlterUniqueTogether(
                    name='soldejour',
                    unique_together={('entreprise', 'date_saisie')},
                ),
            ],
            database_operations=[],
        ),
    ]
