# Generated by Django 5.0.2 on 2026-03-11 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gest_saas', '0003_default_formules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='telephone',
            field=models.CharField(blank=True, default='1', max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Maximum 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalentreprise',
            name='telephone',
            field=models.CharField(blank=True, default='1', max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Maximum 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone'),
            preserve_default=False,
        ),
    ]
