# Generated by Django 5.0.2 on 2026-03-11 09:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnonceEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='annonces/evenements/')),
                ('libelle', models.CharField(blank=True, max_length=150, verbose_name='Libellé')),
                ('lien', models.URLField(blank=True, max_length=500, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Annonce évènement',
                'verbose_name_plural': 'Annonces évènements',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='AnnonceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('image', models.ImageField(blank=True, null=True, upload_to='annonces/infos/')),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Annonce / Information',
                'verbose_name_plural': 'Annonces & Informations',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Banniere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Texte de la bannière')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Contact (téléphone ou autre)')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bannière',
                'verbose_name_plural': 'Bannières',
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('role', models.CharField(max_length=150, verbose_name='Rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipe/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Membre équipe',
                'verbose_name_plural': 'Equipes',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='evenement')),
                ('text', models.TextField(max_length=5000)),
                ('date_saisie', models.DateField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(blank=True, verbose_name='Texte du footer')),
                ('localisation_bp', models.CharField(blank=True, max_length=300, verbose_name='Localisation / B.P.')),
                ('contact_1', models.CharField(blank=True, max_length=100, verbose_name='Contact 1')),
                ('contact_2', models.CharField(blank=True, max_length=100, verbose_name='Contact 2')),
                ('contact_3', models.CharField(blank=True, max_length=100, verbose_name='Contact 3')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
        migrations.CreateModel(
            name='MessageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Message contact',
                'verbose_name_plural': 'Messages contact',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='NosService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('lien_detail', models.URLField(blank=True, max_length=500, null=True, verbose_name='Lien pour détail')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Nos Services',
                'ordering': ['ordre', 'libelle'],
            },
        ),
        migrations.CreateModel(
            name='PageAccueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('texte_accueil', models.TextField(blank=True, help_text="Texte de l'accueil", null=True, verbose_name="Texte de l'accueil")),
                ('background', models.ImageField(blank=True, null=True, upload_to='accueil/backgrounds', verbose_name='Image de fond')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Bloc page d'accueil",
                'verbose_name_plural': "Page d'accueil",
            },
        ),
        migrations.CreateModel(
            name='PageContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Contactez-nous', max_length=200)),
                ('introduction', models.TextField(blank=True, verbose_name="Texte d'introduction")),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('horaires', models.TextField(blank=True, verbose_name="Horaires d'ouverture")),
                ('carte_embed', models.TextField(blank=True, help_text='Code iframe Google Maps ou autre')),
                ('actif_formulaire', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Contact',
                'verbose_name_plural': 'Page Contact',
            },
        ),
        migrations.CreateModel(
            name='PartenSpons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entite', models.CharField(choices=[('partenaire', 'Partenaire'), ('sponsor', 'Sponsor')], default='partenaire', max_length=20, verbose_name='Type')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partenaires_sponsors/')),
                ('lien', models.URLField(blank=True, max_length=500, null=True, verbose_name='Site web')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partenaire / Sponsor',
                'verbose_name_plural': 'Partenaires & Sponsors',
                'ordering': ['type_entite', 'ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='presentation/')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Présentation',
                'verbose_name_plural': 'Présentations',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du réseau')),
                ('icon', models.CharField(blank=True, help_text="Classe CSS ou nom d'icône (ex: fa-facebook)", max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reseaux/')),
                ('lien', models.URLField(max_length=500, verbose_name='Lien')),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Réseau social',
                'verbose_name_plural': 'Réseaux sociaux',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Clic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=200, verbose_name='Élément cliqué (id, texte, lien)')),
                ('url_page', models.CharField(blank=True, max_length=500)),
                ('date_clic', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Clic',
                'verbose_name_plural': 'Clics',
                'ordering': ['-date_clic'],
                'indexes': [models.Index(fields=['date_clic'], name='PBFinance_c_date_cl_5e58c8_idx'), models.Index(fields=['element'], name='PBFinance_c_element_da0e11_idx')],
            },
        ),
        migrations.CreateModel(
            name='StatistiqueAgregee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('jour', 'Journalier'), ('mois', 'Mensuel'), ('annee', 'Annuel')], max_length=10)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('url_visitee', models.CharField(blank=True, max_length=500)),
                ('nombre_visites', models.PositiveIntegerField(default=0)),
                ('nombre_clics', models.PositiveIntegerField(default=0)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Statistique agrégée',
                'verbose_name_plural': 'Statistiques agrégées',
                'indexes': [models.Index(fields=['periode', 'date_debut'], name='PBFinance_s_periode_6b87b8_idx')],
                'unique_together': {('periode', 'date_debut', 'url_visitee')},
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_visitee', models.CharField(max_length=500, verbose_name='URL visitée')),
                ('titre_page', models.CharField(blank=True, max_length=200)),
                ('date_visite', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-date_visite'],
                'indexes': [models.Index(fields=['date_visite'], name='PBFinance_v_date_vi_0f033f_idx'), models.Index(fields=['url_visitee'], name='PBFinance_v_url_vis_4aa53f_idx')],
            },
        ),
    ]
